'use client'
import { useState } from 'react'
import { Copy, Check, Download } from 'lucide-react'

const REMOVABLE_ATTRS = [
  'id', 'class', 'style',
  'data-name', 'data-original',
  'inkscape:label', 'inkscape:groupmode', 'inkscape:connector-curvature',
  'sodipodi:nodetypes',
  'xml:space',
  'enable-background',
  'version',
]

const REMOVABLE_ELEMENTS = [
  'title', 'desc', 'defs',
  'metadata',
  'sodipodi:namedview',
  'inkscape:perspective',
  'rdf:RDF',
  'cc:Work',
  'dc:format',
]

function optimizeSvg(
  input: string,
  opts: {
    removeComments: boolean
    removeMetadata: boolean
    removeEmptyAttrs: boolean
    removeEditorAttrs: boolean
    collapseWhitespace: boolean
  }
): { output: string; originalSize: number; optimizedSize: number } {
  let svg = input

  if (opts.removeComments) {
    svg = svg.replace(/<!--[\s\S]*?-->/g, '')
  }

  if (opts.removeMetadata) {
    for (const el of REMOVABLE_ELEMENTS) {
      svg = svg.replace(new RegExp(`<${el}[^>]*>([\\s\\S]*?)<\\/${el}>`, 'gi'), '')
      svg = svg.replace(new RegExp(`<${el}[^/]*/?>`, 'gi'), '')
    }
  }

  if (opts.removeEditorAttrs) {
    for (const attr of REMOVABLE_ATTRS) {
      // Remove attribute="..." and attribute='...'
      svg = svg.replace(new RegExp(`\\s${attr.replace(':', '\\:')}="[^"]*"`, 'gi'), '')
      svg = svg.replace(new RegExp(`\\s${attr.replace(':', '\\:')}='[^']*'`, 'gi'), '')
    }
    // Remove xmlns:inkscape, xmlns:sodipodi, xmlns:dc, xmlns:cc, xmlns:rdf, xmlns:xlink
    svg = svg.replace(/\s+xmlns:(inkscape|sodipodi|dc|cc|rdf)="[^"]*"/g, '')
  }

  if (opts.removeEmptyAttrs) {
    // Remove attributes with empty string value
    svg = svg.replace(/\s+\w[\w-:]*=""/g, '')
  }

  if (opts.collapseWhitespace) {
    // Collapse runs of whitespace between tags (but not inside attribute values)
    svg = svg
      .split('\n')
      .map((l) => l.trim())
      .filter(Boolean)
      .join('')
    // Normalize space around = in attributes
    svg = svg.replace(/\s*=\s*/g, '=')
    // Collapse multiple spaces in tag content
    svg = svg.replace(/>\s+</g, '><')
  } else {
    // Trim trailing whitespace per line and remove fully blank lines
    svg = svg
      .split('\n')
      .map((l) => l.trimEnd())
      .filter((l) => l.length > 0)
      .join('\n')
  }

  return {
    output: svg.trim(),
    originalSize: new TextEncoder().encode(input).length,
    optimizedSize: new TextEncoder().encode(svg.trim()).length,
  }
}

const EXAMPLE = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Inkscape -->
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   version="1.1"
   id="svg8"
   width="100"
   height="100">
  <metadata id="metadata5">
    <rdf:RDF>
      <cc:Work rdf:about="">
        <dc:format>image/svg+xml</dc:format>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <title>My Icon</title>
  <desc>A simple circle icon</desc>
  <!-- main shape -->
  <circle
     cx="50"
     cy="50"
     r="40"
     fill="#4f46e5"
     id="circle1"
     inkscape:label="circle"
     data-name="main-circle" />
</svg>`

export function SvgOptimizerTool() {
  const [input, setInput] = useState('')
  const [result, setResult] = useState<{ output: string; originalSize: number; optimizedSize: number } | null>(null)
  const [removeComments, setRemoveComments] = useState(true)
  const [removeMetadata, setRemoveMetadata] = useState(true)
  const [removeEmptyAttrs, setRemoveEmptyAttrs] = useState(true)
  const [removeEditorAttrs, setRemoveEditorAttrs] = useState(true)
  const [collapseWhitespace, setCollapseWhitespace] = useState(true)
  const [copied, setCopied] = useState(false)

  const handleRun = () => {
    if (!input.trim()) return
    const res = optimizeSvg(input, { removeComments, removeMetadata, removeEmptyAttrs, removeEditorAttrs, collapseWhitespace })
    setResult(res)
  }

  const handleCopy = async () => {
    if (!result) return
    await navigator.clipboard.writeText(result.output)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownload = () => {
    if (!result) return
    const blob = new Blob([result.output], { type: 'image/svg+xml' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'optimized.svg'
    a.click()
    URL.revokeObjectURL(url)
  }

  const savings = result
    ? Math.max(0, Math.round((1 - result.optimizedSize / result.originalSize) * 100))
    : 0

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap gap-x-6 gap-y-2 text-sm">
        {[
          { label: 'Remove comments', value: removeComments, set: setRemoveComments },
          { label: 'Remove metadata & editor elements', value: removeMetadata, set: setRemoveMetadata },
          { label: 'Remove editor attributes (Inkscape, etc.)', value: removeEditorAttrs, set: setRemoveEditorAttrs },
          { label: 'Remove empty attributes', value: removeEmptyAttrs, set: setRemoveEmptyAttrs },
          { label: 'Collapse whitespace', value: collapseWhitespace, set: setCollapseWhitespace },
        ].map(({ label, value, set }) => (
          <label key={label} className="flex items-center gap-2 cursor-pointer">
            <input type="checkbox" checked={value} onChange={(e) => set(e.target.checked)} className="rounded" />
            {label}
          </label>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <label className="block text-sm font-medium">SVG Input</label>
            <button onClick={() => setInput(EXAMPLE)} className="text-xs text-primary hover:underline">
              Load example
            </button>
          </div>
          <textarea
            value={input}
            onChange={(e) => { setInput(e.target.value); setResult(null) }}
            placeholder="Paste SVG source here..."
            className="input-base h-80 font-mono text-xs resize-none"
            spellCheck={false}
          />
          {input && (
            <p className="text-xs text-muted-foreground">
              {new TextEncoder().encode(input).length} bytes
            </p>
          )}
        </div>

        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <label className="block text-sm font-medium">Optimized Output</label>
            {result && (
              <div className="flex items-center gap-3">
                <span className="text-xs text-muted-foreground">
                  {result.optimizedSize} bytes
                  {savings > 0 && (
                    <span className="ml-1 text-green-600 dark:text-green-400 font-semibold">(-{savings}%)</span>
                  )}
                </span>
                <button onClick={handleCopy} className="flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground">
                  {copied ? <Check size={13} /> : <Copy size={13} />}
                  {copied ? 'Copied' : 'Copy'}
                </button>
              </div>
            )}
          </div>
          {result ? (
            <textarea
              value={result.output}
              readOnly
              className="input-base h-80 font-mono text-xs resize-none bg-muted/30"
              spellCheck={false}
            />
          ) : (
            <div className="border border-border rounded-lg h-80 flex items-center justify-center text-muted-foreground text-sm">
              Optimized SVG will appear here
            </div>
          )}
        </div>
      </div>

      <div className="flex gap-3">
        <button onClick={handleRun} disabled={!input.trim()} className="btn-primary">
          Optimize SVG
        </button>
        {result && (
          <button onClick={handleDownload} className="btn-secondary flex items-center gap-2">
            <Download size={14} />
            Download
          </button>
        )}
      </div>

      {result && savings === 0 && (
        <p className="text-xs text-muted-foreground">
          No size reduction with the current options. Try enabling more options above.
        </p>
      )}
    </div>
  )
}
