export const TOOLS_CATEGORIES = {
  DEVELOPER: 'developer',
  VALIDATION: 'validation',
  FORMATTER: 'formatter',
  CONVERTER: 'converter',
} as const

export const CATEGORY_INFO = {
  [TOOLS_CATEGORIES.DEVELOPER]: {
    name: 'Developer Tools',
    description: 'Essential utilities for development and debugging',
  },
  [TOOLS_CATEGORIES.VALIDATION]: {
    name: 'Validation Tools',
    description: 'Validate and parse code and data formats',
  },
  [TOOLS_CATEGORIES.FORMATTER]: {
    name: 'Formatter Tools',
    description: 'Format and beautify code and data',
  },
  [TOOLS_CATEGORIES.CONVERTER]: {
    name: 'Converter Tools',
    description: 'Convert between different formats and encodings',
  },
} as const

export const TOOLS = [
  // Developer Tools
  {
    id: 'rest-api-tester',
    name: 'REST API Tester',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'Test REST APIs with custom headers and body',
    shortDescription: 'Test REST APIs',
    comingSoon: true,
  },
  {
    id: 'js-minifier',
    name: 'JavaScript Minifier',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'Minify JavaScript code to reduce file size',
    shortDescription: 'Minify JavaScript',
  },
  {
    id: 'js-beautifier',
    name: 'JavaScript Beautifier',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'Format and beautify JavaScript code',
    shortDescription: 'Beautify JavaScript',
  },
  {
    id: 'css-minifier',
    name: 'CSS Minifier',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'Minify CSS code to reduce file size',
    shortDescription: 'Minify CSS',
  },
  {
    id: 'css-beautifier',
    name: 'CSS Beautifier',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'Format and beautify CSS code',
    shortDescription: 'Beautify CSS',
  },
  {
    id: 'json-minifier',
    name: 'JSON Minifier',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'Minify JSON to reduce file size',
    shortDescription: 'Minify JSON',
  },
  {
    id: 'json-beautifier',
    name: 'JSON Beautifier',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'Format and beautify JSON data',
    shortDescription: 'Beautify JSON',
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'Convert between Unix timestamps and readable dates',
    shortDescription: 'Convert timestamps',
  },
  {
    id: 'json-generator',
    name: 'JSON Generator',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'Generate valid JSON with random data',
    shortDescription: 'Generate JSON',
  },
  {
    id: 'color-code-picker',
    name: 'Color Code Picker',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'Convert between HEX, RGB, and HSL color formats',
    shortDescription: 'Pick color codes',
  },
  {
    id: 'har-viewer',
    name: 'HAR Viewer',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'View and analyze HTTP Archive (HAR) files',
    shortDescription: 'View HAR files',
    comingSoon: true,
  },
  {
    id: 'url-splitter',
    name: 'URL Splitter',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'Parse and decompose URLs into components',
    shortDescription: 'Split URLs',
  },
  {
    id: 'code-cleaner',
    name: 'Code Cleaner',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'Remove comments and unnecessary whitespace from code',
    shortDescription: 'Clean code',
  },
  {
    id: 'diff-checker',
    name: 'Diff Checker',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'Compare two texts and highlight differences',
    shortDescription: 'Check differences',
  },
  {
    id: 'url-encoder-decoder',
    name: 'URL Encoder/Decoder',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'Encode and decode URLs and special characters',
    shortDescription: 'Encode/decode URLs',
  },
  {
    id: 'mime-type-checker',
    name: 'MIME Type Checker',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'Identify MIME types by file extension',
    shortDescription: 'Check MIME types',
  },
  {
    id: 'har-sanitizer',
    name: 'HAR Sanitizer',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'Remove sensitive data from HAR files',
    shortDescription: 'Sanitize HAR files',
    comingSoon: true,
  },
  {
    id: 'html-encoder-decoder',
    name: 'HTML Encoder/Decoder',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'Encode and decode HTML entities',
    shortDescription: 'Encode/decode HTML',
  },
  {
    id: 'js-string-escaper',
    name: 'JavaScript String Escaper',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'Escape special characters in JavaScript strings',
    shortDescription: 'Escape JS strings',
  },
  {
    id: 'base64-encoder',
    name: 'Base64 Encoder',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'Encode text to Base64 format',
    shortDescription: 'Encode to Base64',
  },
  {
    id: 'base64-decoder',
    name: 'Base64 Decoder',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'Decode Base64 text back to plain text',
    shortDescription: 'Decode Base64',
  },
  {
    id: 'svg-viewer',
    name: 'SVG Viewer',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'View and edit SVG code with live preview',
    shortDescription: 'View SVG',
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'Decode and inspect JWT tokens',
    shortDescription: 'Decode JWT',
  },
  {
    id: 'xml-string-escaper',
    name: 'XML String Escaper',
    category: TOOLS_CATEGORIES.DEVELOPER,
    description: 'Escape special characters in XML strings',
    shortDescription: 'Escape XML strings',
  },

  // Validation Tools
  {
    id: 'regex-parser',
    name: 'Regex Parser',
    category: TOOLS_CATEGORIES.VALIDATION,
    description: 'Test and validate regular expressions',
    shortDescription: 'Parse regex',
  },
  {
    id: 'json-path-evaluator',
    name: 'JSON Path Evaluator',
    category: TOOLS_CATEGORIES.VALIDATION,
    description: 'Query JSON using JSONPath expressions',
    shortDescription: 'Evaluate JSONPath',
    comingSoon: true,
  },
  {
    id: 'xpath-evaluator',
    name: 'XPath Evaluator',
    category: TOOLS_CATEGORIES.VALIDATION,
    description: 'Query XML using XPath expressions',
    shortDescription: 'Evaluate XPath',
    comingSoon: true,
  },
  {
    id: 'html-validator',
    name: 'HTML Validator',
    category: TOOLS_CATEGORIES.VALIDATION,
    description: 'Validate HTML markup and check for errors',
    shortDescription: 'Validate HTML',
    comingSoon: true,
  },
  {
    id: 'redirection-checker',
    name: 'Redirection Checker',
    category: TOOLS_CATEGORIES.VALIDATION,
    description: 'Follow HTTP redirects and check final URL',
    shortDescription: 'Check redirects',
    comingSoon: true,
  },
  {
    id: 'link-checker',
    name: 'Link Checker',
    category: TOOLS_CATEGORIES.VALIDATION,
    description: 'Check if URLs are valid and accessible',
    shortDescription: 'Check links',
    comingSoon: true,
  },
  {
    id: 'jsonpath-finder',
    name: 'JSONPath Finder',
    category: TOOLS_CATEGORIES.VALIDATION,
    description: 'Find and extract data using JSONPath',
    shortDescription: 'Find JSONPath',
    comingSoon: true,
  },
  {
    id: 'yaml-validator',
    name: 'YAML Validator',
    category: TOOLS_CATEGORIES.VALIDATION,
    description: 'Validate YAML syntax and structure',
    shortDescription: 'Validate YAML',
  },
  {
    id: 'js-validator',
    name: 'JavaScript Validator',
    category: TOOLS_CATEGORIES.VALIDATION,
    description: 'Validate JavaScript code syntax',
    shortDescription: 'Validate JavaScript',
  },

  // Formatter Tools
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    category: TOOLS_CATEGORIES.FORMATTER,
    description: 'Format JSON with custom indentation',
    shortDescription: 'Format JSON',
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    category: TOOLS_CATEGORIES.FORMATTER,
    description: 'Format and indent XML code',
    shortDescription: 'Format XML',
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    category: TOOLS_CATEGORIES.FORMATTER,
    description: 'Format SQL queries with proper indentation',
    shortDescription: 'Format SQL',
  },
  {
    id: 'html-formatter',
    name: 'HTML Formatter',
    category: TOOLS_CATEGORIES.FORMATTER,
    description: 'Format HTML with consistent indentation',
    shortDescription: 'Format HTML',
  },
  {
    id: 'html-beautifier',
    name: 'HTML Beautifier',
    category: TOOLS_CATEGORIES.FORMATTER,
    description: 'Beautify and clean up HTML code',
    shortDescription: 'Beautify HTML',
  },

  // Converter Tools
  {
    id: 'json-to-protobuf',
    name: 'JSON to Protobuf',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Convert JSON data to Protocol Buffer format',
    shortDescription: 'JSON to Protobuf',
    comingSoon: true,
  },
  {
    id: 'json-to-java',
    name: 'JSON to Java',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Convert JSON to Java POJO classes',
    shortDescription: 'JSON to Java',
  },
  {
    id: 'json-to-xml',
    name: 'JSON to XML',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Convert JSON data to XML format',
    shortDescription: 'JSON to XML',
  },
  {
    id: 'json-to-php',
    name: 'JSON to PHP',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Convert JSON to PHP array syntax',
    shortDescription: 'JSON to PHP',
  },
  {
    id: 'json-to-csharp',
    name: 'JSON to C#',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Convert JSON to C# class definitions',
    shortDescription: 'JSON to C#',
  },
  {
    id: 'xml-to-xsd',
    name: 'XML to XSD',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Generate XSD schema from XML document',
    shortDescription: 'XML to XSD',
    comingSoon: true,
  },
  {
    id: 'xml-to-yaml',
    name: 'XML to YAML',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Convert XML data to YAML format',
    shortDescription: 'XML to YAML',
  },
  {
    id: 'xml-to-json',
    name: 'XML to JSON',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Convert XML data to JSON format',
    shortDescription: 'XML to JSON',
  },
  {
    id: 'sql-to-mongodb',
    name: 'SQL to MongoDB',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Convert SQL queries to MongoDB syntax',
    shortDescription: 'SQL to MongoDB',
    comingSoon: true,
  },
  {
    id: 'ini-to-json',
    name: 'INI to JSON',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Convert INI configuration to JSON',
    shortDescription: 'INI to JSON',
  },
  {
    id: 'ini-to-xml',
    name: 'INI to XML',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Convert INI configuration to XML',
    shortDescription: 'INI to XML',
  },
  {
    id: 'ini-to-yaml',
    name: 'INI to YAML',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Convert INI configuration to YAML',
    shortDescription: 'INI to YAML',
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Convert CSV data to JSON array',
    shortDescription: 'CSV to JSON',
  },
  {
    id: 'csv-to-xml',
    name: 'CSV to XML',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Convert CSV data to XML format',
    shortDescription: 'CSV to XML',
  },
  {
    id: 'csv-to-yaml',
    name: 'CSV to YAML',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Convert CSV data to YAML format',
    shortDescription: 'CSV to YAML',
  },
  {
    id: 'csv-to-sql',
    name: 'CSV to SQL',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Convert CSV data to SQL INSERT statements',
    shortDescription: 'CSV to SQL',
  },
  {
    id: 'image-to-data-uri',
    name: 'Image to Data URI',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Convert image files to Data URI format',
    shortDescription: 'Image to Data URI',
  },
  {
    id: 'data-uri-to-image',
    name: 'Data URI to Image',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Convert Data URI back to downloadable image',
    shortDescription: 'Data URI to Image',
  },
  {
    id: 'yaml-to-json',
    name: 'YAML to JSON',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Convert YAML to JSON format',
    shortDescription: 'YAML to JSON',
  },
  {
    id: 'json-to-yaml',
    name: 'JSON to YAML',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Convert JSON to YAML format',
    shortDescription: 'JSON to YAML',
  },
  {
    id: 'rgb-to-hex',
    name: 'RGB to HEX',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Convert RGB color values to HEX format',
    shortDescription: 'RGB to HEX',
  },
  {
    id: 'hex-to-rgb',
    name: 'HEX to RGB',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Convert HEX color values to RGB format',
    shortDescription: 'HEX to RGB',
  },
  {
    id: 'idn-converter',
    name: 'IDN Converter',
    category: TOOLS_CATEGORIES.CONVERTER,
    description: 'Convert between Unicode and Punycode domain names',
    shortDescription: 'Convert IDN',
  },
] as const
