/**
 * MCP tool utilities — safe to import on both server and client.
 *
 * The actual source of truth is toolHandlers in tool-handlers.ts (server-only).
 * The MCP docs page imports toolHandlers directly (server component).
 * This file re-exports a pre-computed ID set for use in client components.
 *
 * NOTE: If you add a handler to tool-handlers.ts you MUST add its id here too.
 * This is the only file that needs updating when adding a new MCP tool.
 */

export const MCP_TOOL_IDS: readonly string[] = [
  // Formatter
  'js-minifier',
  'js-beautifier',
  'css-minifier',
  'css-beautifier',
  'json-minifier',
  'json-beautifier',
  'json-formatter',
  'xml-formatter',
  'html-formatter',
  'html-beautifier',
  'sql-formatter',
  'sql-minifier',
  'graphql-formatter',
  'markdown-formatter',
  // Converter
  'timestamp-converter',
  'timezone-converter',
  'iso8601-converter',
  'url-encoder-decoder',
  'html-encoder-decoder',
  'js-string-escaper',
  'xml-string-escaper',
  'base64-encoder',
  'base64-decoder',
  'base64-encoder-decoder',
  'text-case-converter',
  'color-code-picker',
  'rgb-to-hex',
  'hex-to-rgb',
  'idn-converter',
  'unit-converter',
  'currency-converter',
  'json-to-java',
  'json-to-xml',
  'json-to-php',
  'json-to-csharp',
  'json-to-yaml',
  'yaml-to-json',
  'xml-to-yaml',
  'xml-to-json',
  'ini-to-json',
  'ini-to-xml',
  'ini-to-yaml',
  'ini-converter',
  'csv-to-json',
  'csv-to-xml',
  'csv-to-yaml',
  'csv-to-sql',
  'csv-converter',
  'sql-to-mongodb',
  'excel-to-json',
  'excel-to-markdown',
  'pdf-to-markdown',
  'docx-to-markdown',
  'html-to-markdown',
  'markdown-to-html',
  // Developer
  'json-generator',
  'jwt-decoder',
  'url-splitter',
  'mime-type-checker',
  'code-cleaner',
  'diff-checker',
  'public-ip-lookup',
  'uuid-generator',
  'hash-generator',
  'password-generator',
  'mock-data-generator',
  'qr-code-generator',
  'favicon-generator',
  'rest-api-tester',
  'business-day-calculator',
  'relative-date-calculator',
  'age-calculator',
  'env-file-parser',
  'gitignore-generator',
  'conventional-commit-generator',
  'hmac-generator',
  'bcrypt-tool',
  'file-hash-checker',
  'dns-lookup',
  'whois-lookup',
  'ssl-checker',
  'cidr-calculator',
  'ip-range-calculator',
  'markdown-table-generator',
  // Validation
  'regex-parser',
  'yaml-validator',
  'js-validator',
  'html-validator',
  'redirection-checker',
  'json-path-evaluator',
  'xpath-evaluator',
  'link-checker',
  'jsonpath-finder',
  'semver-comparator',
  'markdown-linter',
  'openapi-validator',
  'sql-validator',
  // AI Tools (credentials passed as parameters in each call)
  'ai-chat',
  'code-generator',
  'content-summarizer',
  'sentiment-analyzer',
  'ai-code-reviewer',
  'ai-doc-generator',
  'ai-test-generator',
  'ai-sql-builder',
  'ai-schema-generator',
  'researcher-agent',
  'workflow-builder',
  'ai-commit-generator',
  'ai-regex-generator',
  'ai-error-explainer',
  'ai-log-analyzer',
  'ai-dockerfile-generator',
  'ai-architecture-diagram',
  'ai-prompt-optimizer',
  'ai-release-notes',
  'ai-email-generator',
  'ai-social-post',
] as const

export const MCP_TOOL_ID_SET: ReadonlySet<string> = new Set(MCP_TOOL_IDS)

export function isMcpEnabled(toolId: string): boolean {
  return MCP_TOOL_ID_SET.has(toolId)
}
